//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArvinReyes.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Patient
    {
        [Key]
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> FileNo { get; set; }
        public string CitizenId { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public Nullable<byte> Gender { get; set; }
        public string Nationality { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string ContactPerson { get; set; }
        public string ContactRelation { get; set; }
        public string ContactPhone { get; set; }
        public string Photo { get; set; }
        public Nullable<System.DateTime> FirstVisitDate { get; set; }
        public Nullable<System.DateTime> RecordCreationDate { get; set; }

        //public Patient() {
        //    this.Id = new Guid();
        //    this.Name = "";
        //    this.FileNo = 0;
        //    this.CitizenId = "";
        //    this.Birthdate = null;
        //    this.Gender = 0;
        //    this.Nationality = "";
        //    this.PhoneNumber = "";
        //    this.Email = "";
        //    this.Country = "";
        //    this.City = "";
        //    this.Street = "";
        //    this.Address1 = "";
        //    this.Address2 = "";
        //    this.ContactPerson = "";
        //    this.ContactRelation = "";
        //    this.ContactPhone = "";
        //    this.Photo = new byte[0];
        //    this.FileName = "";
        //    this.FirstVisitDate = null;
        //    this.RecordCreationDate = null;
        //}
    }
}
